    gallaryData  = [
        { "path": 'images/galllery/images/10 cut.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/cushion 9 hole.jpg',"type":"product"},
        { "path": 'images/galllery/images/oval.jpg',"type":"product"},
        { "path": 'images/galllery/images/12cut.jpg'  ,"type":"product"},
        { "path": 'images/galllery/images/dome set.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/15cut.jpg',"type":"product"},
        { "path": 'images/galllery/images/flower 3hole.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/pears.jpg',"type":"product"},
        { "path": 'images/galllery/images/4v prong.jpg'  ,"type":"product"},
        { "path": 'images/galllery/images/flower.jpg'  ,"type":"product"},
        { "path": 'images/galllery/images/rolex cut.jpg',"type":"product"},
        { "path": 'images/galllery/images/8+1 combo set.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/marquise 24cut.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/square 16hole.jpg',"type":"product"},
        { "path": 'images/galllery/images/8+1 multicluster.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/marquise 2 hole.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/square 9hole set.jpg',"type":"product"},
        { "path": 'images/galllery/images/8 cut.jpg' ,"type":"product"},
        { "path": 'images/galllery/images/oval 2 hole.jpg',"type":"product"},
        { "path": 'images/galllery/images/pears 24cut.jpg',"type":"product"},
        { "path" : 'images/galllery/1.png',"type":"photos"},
        { "path" : 'images/galllery/2.png',"type":"photos"},
        { "path" : 'images/galllery/3.png',"type":"photos"},
        { "path" : 'images/galllery/4.png',"type":"photos"},
        { "path" : 'images/galllery/5.png',"type":"photos"},
        { "path" : 'images/galllery/6.png',"type":"photos"},
        { "path" : 'images/galllery/7.png',"type":"photos"},
        { "path" : 'images/galllery/8.png',"type":"photos"},
        { "path" : 'images/galllery/9.png',"type":"photos"},
        { "path" : 'images/galllery/10.png',"type":"photos"}
        
    ];